# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: sushi-api
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: extractor
      context: .
      docker:
        dockerfile: Dockerfile.extractor
    - image: router
      context: .
      docker:
        dockerfile: Dockerfile.router
        # buildArgs:
        #   TURBO_TEAM: "teamsushi"
        #   TURBO_TOKEN:{{ .TURBO_TOKEN }}
deploy:
  helm:
    releases:
      - name: sushi-api
        chartPath: k8s/chart
manifests:
  rawYaml:
    - k8s/ingress-local.yaml
profiles:
- name: local
- name: staging
  build:
    googleCloudBuild:
      projectId: "sushi-api-414412"
  manifests:
    rawYaml:
      - k8s/ingress-staging.yaml
- name: production
  build:
    googleCloudBuild:
      projectId: "sushi-api-414412"
  manifests:
    rawYaml:
      - k8s/ingress-production.yaml