{{- range .Values.chains }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: extractor-{{ .id }}-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: extractor-{{ .id }}
  updatePolicy:
    updateMode: "Auto"
    minReplicas: 1
  resourcePolicy:
    containerPolicies:
      - containerName: extractor
        minAllowed:
          cpu: "500m"
          memory: "2Gi"
        maxAllowed:
          cpu: "1000m"
          memory: "4Gi"
        controlledResources: ["cpu", "memory"]
{{- end }}