{{- range .Values.chains }}
apiVersion: v1
kind: Service
metadata:
  name: router-{{ .id }}
  labels:
    app: router-{{ .id }}
spec:
  selector:
    app: router-{{ .id }}
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
{{- end }}