
chains:
  - name: "ethereum"
    id: "1"
  - name: "optimism"
    id: "10"
  - name: "cronos"
    id: "25"
  - name: "telos"
    id: "40"
  - name: "bsc"
    id: "56"
  - name: "gnosis"
    id: "100"
  - name: "thundercore"
    id: "108"
  - name: "fuse"
    id: "122"
  - name: "polygon"
    id: "137"
  - name: "bttc"
    id: "199"
  - name: "fantom"
    id: "250"
  - name: "boba"
    id: "288"
  - name: "filecoin"
    id: "314"
  - name: "polygon-zkevm"
    id: "1101"
  - name: "core"
    id: "1116"
  - name: "moonbeam"
    id: "1284"
  - name: "moonriver"
    id: "1285"
  - name: "metis"
    id: "1088"
  - name: "kava"
    id: "2222"
  - name: "zetachain"
    id: "7000"
  - name: "base"
    id: "8453"
  - name: "haqq"
    id: "11235"
  - name: "arbitrum"
    id: "42161"
  - name: "arbitrum-nova"
    id: "42170"
  - name: "celo"
    id: "42220"
  - name: "avalanche"
    id: "43114"
  - name: "linea"
    id: "59144"
  - name: "boba-bnb"
    id: "56288"
  - name: "scroll"
    id: "534352"
  - name: "harmony"
    id: "1666600000"